[package]
name = "glossy"
version = "0.1.1"
authors = ["Michael Thomas <Michaelt293@gmail.com>"]

[dependencies]
clap = "~2.19.0"
csv = "1.0.0-beta.1"
serde = "1"
serde_derive = "1"


[[bin]]
bench = false
path = "src/main.rs"
name = "glo"
